// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANtoEMrbU03bVo7elEI_CPphKa-4Aw6lQ',
    appId: '1:574028162352:web:742811df81a9e0c74114f5',
    messagingSenderId: '574028162352',
    projectId: 'pesaserve',
    authDomain: 'pesaserve.firebaseapp.com',
    storageBucket: 'pesaserve.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnbO9nuadNye9eb4UFjIkGM51Yi_hTB14',
    appId: '1:574028162352:android:9055c5d3901cb4d84114f5',
    messagingSenderId: '574028162352',
    projectId: 'pesaserve',
    storageBucket: 'pesaserve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CtTqHHfB1d-AU_Zr7zgqxp3maTKf-UE',
    appId: '1:574028162352:ios:5d40a71bf4cc37c74114f5',
    messagingSenderId: '574028162352',
    projectId: 'pesaserve',
    storageBucket: 'pesaserve.firebasestorage.app',
    iosBundleId: 'com.example.pesaserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9CtTqHHfB1d-AU_Zr7zgqxp3maTKf-UE',
    appId: '1:574028162352:ios:5d40a71bf4cc37c74114f5',
    messagingSenderId: '574028162352',
    projectId: 'pesaserve',
    storageBucket: 'pesaserve.firebasestorage.app',
    iosBundleId: 'com.example.pesaserve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANtoEMrbU03bVo7elEI_CPphKa-4Aw6lQ',
    appId: '1:574028162352:web:567f897fb865f12c4114f5',
    messagingSenderId: '574028162352',
    projectId: 'pesaserve',
    authDomain: 'pesaserve.firebaseapp.com',
    storageBucket: 'pesaserve.firebasestorage.app',
  );
}
